kind: Deployment
apiVersion: apps/v1
metadata:
  name: shippingservice-deploy
  namespace: {{ .Values.namespace }}
  labels:
    app: shippingservice
spec:
  replicas: {{ .Values.shippingservice.replicasCount }}
  strategy:
        type: {{ .Values.strategy.type }}
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
        - name: shippingservice
          image: namanss/shippingservice:{{ .Values.shippingservice.imagetag }}
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"
            - name: DISABLE_TRACING
              value: "true"
            - name: DISABLE_PROFILER
              value: "true"
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
---
kind: Service
apiVersion: v1
metadata:
  name: shippingservice-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: shippingservice
spec:
  selector:
    app: shippingservice
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: {{ .Values.shippingservice.servicetype }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: shippingservice-sa
  namespace: {{ .Values.namespace }}
  labels:
    app: shippingservice