kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: online-app
  namespace: argocd
spec:
  description: Project space for Online Web-Store Application
  sourceRepos:
    - '*'
  destinations:
    -  server: https://kubernetes.default.svc
ClusterResourceWhitelist:
  - group: '*'
    namespace: '*' #for principle of least privilage replace it with the application namespace